### ISSUE TITLE
Support official way to include Qt Headers

### ISSUE THREAD

**Issue by Vertexwahn** [Vertexwahn/rules_qt6#12]
It seems that the official documentation has ways of including stuff that is not supported by `rules_qt6` https://doc.qt.io/qt-6/qtwidgets-tutorials-notepad-example.html

For instance, for the QSettings class, we need to include `#include "QtCore/QSettings"` where the [official Qt documentation](https://doc.qt.io/qt-6/qsettings.html) says `#include <QSettings>` is sufficient.

Expected fix: Add a demo to the test folder that uses for instance `#include <QSettings>`. Fix the rules to make this working an all platforms (Windows, macOS, Linux).

**Comment by ankit-agarwal1999** [comment]
This should be a one-liner (at least for linux): 
```
diff --git qt_linux_x86_64.BUILD qt_linux_x86_64.BUILD
index ffa968a..e52b8ae 100644
--- qt_linux_x86_64.BUILD
+++ qt_linux_x86_64.BUILD
@@ -7,7 +7,7 @@ load("@rules_qt//:qt_libraries.bzl", "QT_LIBRARIES")
             "lib/lib%s.so*" % library_name,
         ]),
         hdrs = glob(["include/%s/**" % include_folder]),
-        includes = ["include"],
+        includes = ["include", "include/%s" % include_folder],
         target_compatible_with = ["@platforms//os:linux"],
         visibility = ["//visibility:public"],
     )
```

**Comment by Vertexwahn** [comment]
Fixed by https://github.com/Vertexwahn/rules_qt6/pull/16

Thanks @ankit-agarwal1999 and @dieortin!
