### ISSUE TITLE
Add "strip_include_prefix" parameter into "qt_cc_library" rule.

### ISSUE THREAD

**Issue by mehandes** [Vertexwahn/rules_qt6#19]
Strandard 'cc_library' rule supports ''strip_include_prefix" parameter, which is usefull when you creating custom libraries.

**Comment by Vertexwahn** [comment]
If you provide a pull request I can merge it

**Comment by mehandes** [comment]
Sorry, I didn't notice "**kwargs" in function defenition. My fault
